# Generated by Django 3.2.9 on 2021-12-10 07:35

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_weblog', to='account.weblog', verbose_name='مالک')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='پدر')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_weblog', to='account.weblog', verbose_name='مالک')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=12, max_length=12, unique=True, verbose_name='آدرس')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('publish_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'انتشار'), ('DRAFT', 'پیش نویس')], default='PU', max_length=10, verbose_name='وضعیت')),
                ('like_count', models.IntegerField(default=0, verbose_name='لایک')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='دسته')),
                ('like', models.ManyToManyField(blank=True, related_name='blog_like', to=settings.AUTH_USER_MODEL, verbose_name='لایک')),
                ('tag', models.ManyToManyField(related_name='tag_owner', to='blog.Tag', verbose_name='تگ')),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.weblog', verbose_name='وبلاگ')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
            ],
        ),
    ]
