# Generated by Django 3.2.9 on 2021-12-07 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20211207_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='blog_like', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
