# Generated by Django 3.2.9 on 2021-12-04 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('Religious', 'مذهبی'), ('politicalـandـsocial', 'سیاسی و اجتماعی'), ('CultureـandـArt', 'فرهنگ و هنر'), ('sportـandـentertainment', 'ورزش و سرگرمی'), ('Educationalـandـscientific', 'آموزشی و علمی'), ('lifeـstyle', 'سبک زندگی'), ('Economical', 'اقتصادی'), ('medical', 'پزشکی'), ('Personal', 'شخصی')], default='PE', max_length=26, verbose_name='نوع')),
                ('biography', models.TextField(verbose_name='شرح')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
